#ifndef ALT_C2H_HW_DRAW_INT_MANDELBROT_IRQ_H

#define ALT_C2H_HW_DRAW_INT_MANDELBROT_IRQ_H
#include "io.h"


#include "c2h_accelerator_base_addresses.h"

#define ACCELERATOR_MANDELBROT_HW_DRAW_INT_MANDELBROT_MANAGED_INSTANCE_GET_RETURN_VALUE() (( void )IORD_32DIRECT(ACCELERATOR_MANDELBROT_HW_DRAW_INT_MANDELBROT_MANAGED_INSTANCE_CPU_INTERFACE0_BASE,(1*sizeof(int))))
#define ACCELERATOR_MANDELBROT_HW_DRAW_INT_MANDELBROT_MANAGED_INSTANCE_CLEAR_IRQ() (IOWR_32DIRECT(ACCELERATOR_MANDELBROT_HW_DRAW_INT_MANDELBROT_MANAGED_INSTANCE_CPU_INTERFACE0_BASE, (0*sizeof(int)), 0))
#define ACCELERATOR_MANDELBROT_HW_DRAW_INT_MANDELBROT_MANAGED_INSTANCE_BUSY() (IORD_32DIRECT(ACCELERATOR_MANDELBROT_HW_DRAW_INT_MANDELBROT_MANAGED_INSTANCE_CPU_INTERFACE0_BASE, ((0*sizeof(int))) & 1) ^ 1)

#endif /* ALT_C2H_HW_DRAW_INT_MANDELBROT_IRQ_H */

