# c2h.mk
#
# Generated by nios2-c2h-generate-makefile
# Thu Sep 20 15:33:23 2012
#
# Original command:
# nios2-c2h-generate-makefile
#    --sopc=../../../system.sopcinfo
#    --app_dir=.
#    --accelerator=hw_draw_int_mandelbrot,hw_mandelbrot.c,1,0

PTF := ../../../system.sopcinfo

C2H_QUARTUS_COMPILATION = FALSE
FORCE_C2H_RECOMPILE = TRUE
C2H_REPORT_ONLY = FALSE
C2H_NO_GENERATE = FALSE

# Target CPU name for use by chac-generate
C2H_TARGET_CPU = $(CPU_NAME)

APP_DIR := .
APP_CONFIG := .
OBJ_DIR := $(OBJ_ROOT_DIR)
PROJECT := $(basename $(ELF))

C2H_SRC = hw_mandelbrot.c

# Accelerated functions in file: hw_mandelbrot.c
hw_mandelbrot_AC=hw_mandelbrot
$(hw_mandelbrot_AC)_C2H_ACCELERATORS = hw_draw_int_mandelbrot
hw_mandelbrot_EN=hw_mandelbrot
$(hw_mandelbrot_EN)_C2H_ENABLED_ACCELERATORS = hw_draw_int_mandelbrot
hw_mandelbrot_FL=hw_mandelbrot
$(hw_mandelbrot_FL)_C2H_DCACHE_FLUSH = 

