create_module accelerator_mandelbrot_hw_draw_int_mandelbrot accelerator_mandelbrot_hw_draw_int_mandelbrot_managed_instance
create_connection accelerator_mandelbrot_hw_draw_int_mandelbrot_managed_instance.accelerator_mandelbrot_hw_draw_int_mandelbrot_master_resource1/frame_buffer_pipeline_bridge.s1
create_connection accelerator_mandelbrot_hw_draw_int_mandelbrot_managed_instance.accelerator_mandelbrot_hw_draw_int_mandelbrot_master_resource0/colour_lookup_table.s2
create_connection accelerator_mandelbrot_hw_draw_int_mandelbrot_managed_instance.dummy_master/accelerator_mandelbrot_hw_draw_int_mandelbrot_managed_instance.dummy_slave
create_connection accelerator_mandelbrot_hw_draw_int_mandelbrot_managed_instance.internal_master0/accelerator_mandelbrot_hw_draw_int_mandelbrot_managed_instance.sub_hw_draw_int_mandelbrot0
create_connection cpu.data_master/accelerator_mandelbrot_hw_draw_int_mandelbrot_managed_instance.cpu_interface0
create_connection system_clk.clk/accelerator_mandelbrot_hw_draw_int_mandelbrot_managed_instance.clock
create_connection system_clk.clk/accelerator_mandelbrot_hw_draw_int_mandelbrot_managed_instance.cpu_clock
auto_assign_base_addresses accelerator_mandelbrot_hw_draw_int_mandelbrot_managed_instance
set_avalon_base_address accelerator_mandelbrot_hw_draw_int_mandelbrot_managed_instance.sub_hw_draw_int_mandelbrot0 0

