project_open -current_revision "D:/My_RegressionTest/My_120/Cyclone_III_SK/cycloneIII_3c25_start/examples - Copy/cycloneiii_3c25_start_niosii_standard/cycloneIII_3c25_start_niosII_standard.qpf"
set_global_assignment -name QIP_FILE "cycloneIII_3c25_start_niosII_standard_sopc.qip"
project_close
