# TCL File Generated by Component Editor 7.2sp1 on:
# Tue Feb 19 16:36:18 PST 2008
# DO NOT MODIFY

set_source_file "dummy_master.v"
set_module "dummy_master"
set_module_description "This master contains no logic.  It's used to simply connect to unused slave ports for generation to occur"
set_module_property "author" "JCJB"
set_module_property "className" "dummy_master"
set_module_property "displayName" ""
set_module_property "group" "Custom"
set_module_property "instantiateInSystemModule" "true"
set_module_property "simulationFiles" "dummy_master.v"
set_module_property "synthesisFiles" "dummy_master.v"

# Module parameters

# Interface clock_sink
add_interface "clock_sink" "clock" "sink" "asynchronous"
# Ports in interface clock_sink

# Interface m0
add_interface "m0" "avalon" "master" "clock_sink"
set_interface_property "m0" "burstOnBurstBoundariesOnly" "false"
set_interface_property "m0" "doStreamReads" "false"
set_interface_property "m0" "linewrapBursts" "false"
set_interface_property "m0" "doStreamWrites" "false"
# Ports in interface m0
add_port_to_interface "m0" "address" "address"
add_port_to_interface "m0" "writedata" "writedata"
add_port_to_interface "m0" "write" "write"
add_port_to_interface "m0" "waitrequest" "waitrequest"
