#!/bin/bash
#
# This script creates the ucosii Board Support Package (BSP) for picture_viewer

BSP_TYPE=ucosii
BSP_DIR=.
SOPC_DIR=../../..

# Run nios2-bsp utility to create a HAL BSP in this directory
# for the system with a .sopc file in $SOPC_DIR.
cmd="nios2-bsp $BSP_TYPE $BSP_DIR $SOPC_DIR --default_sections_mapping ssram --cmd add_section_mapping .heap ddr_sdram --set hal.make.bsp_cflags_optimization -O3"

echo "create-this-bsp: Running \"$cmd\""
$cmd || {
    echo "$cmd failed"
    exit 1
}

echo "create-this-bsp: Running make"
make
