project_open -current_revision "D:/regtest_111/c3_3c25_neek/neek_sopc/cycloneiii_3c25_niosii_application_selector/cycloneIII_3c25_niosII_application_selector.qpf"
set_global_assignment -name QIP_FILE "cycloneIII_3c25_niosII_application_selector_sopc.qip"
project_close
